const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Admin = sequelize.define('Admin', { name: { type: DataTypes.STRING(120), allowNull: false }, email: { type: DataTypes.STRING(160), allowNull: false, unique: true, validate: { isEmail: true } }, password: { type: DataTypes.STRING(255), allowNull: false } }, { tableName: 'admin' });
const Company = sequelize.define('Company', { name: { type: DataTypes.STRING(160), allowNull: false }, logo: DataTypes.STRING, description: DataTypes.TEXT, website: DataTypes.STRING, email: { type: DataTypes.STRING(160), validate: { isEmail: true } }, phone: DataTypes.STRING(30), address: DataTypes.TEXT, industry: DataTypes.STRING(120), status: { type: DataTypes.ENUM('active', 'inactive'), defaultValue: 'active' } }, { tableName: 'companies' });
const Job = sequelize.define('Job', { companyId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, field: 'company_id' }, title: { type: DataTypes.STRING(180), allowNull: false }, slug: { type: DataTypes.STRING(220), allowNull: false, unique: true }, image: DataTypes.STRING(255), location: { type: DataTypes.STRING(160), allowNull: false }, jobType: { type: DataTypes.STRING(80), allowNull: false, field: 'job_type' }, description: { type: DataTypes.TEXT, allowNull: false }, requirements: { type: DataTypes.TEXT, allowNull: false }, skills: { type: DataTypes.TEXT, allowNull: false }, education: { type: DataTypes.STRING(180), allowNull: false }, salary: DataTypes.STRING(255), deadline: DataTypes.DATEONLY, status: { type: DataTypes.ENUM('draft', 'published', 'closed'), defaultValue: 'draft' } }, { tableName: 'jobs' });
const Application = sequelize.define('Application', { jobId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, field: 'job_id' }, name: { type: DataTypes.STRING(160), allowNull: false }, nisn: { type: DataTypes.STRING(30), allowNull: false }, whatsapp: { type: DataTypes.STRING(30), allowNull: false }, email: { type: DataTypes.STRING(160), allowNull: false, validate: { isEmail: true } }, graduationYear: { type: DataTypes.SMALLINT, allowNull: false, field: 'graduation_year' }, averageScore: { type: DataTypes.DECIMAL(5, 2), allowNull: false, field: 'average_score' }, major: { type: DataTypes.STRING(160), allowNull: false }, mainSkill: { type: DataTypes.STRING(160), allowNull: false, field: 'main_skill' }, cv: { type: DataTypes.STRING(255), allowNull: false }, diploma: { type: DataTypes.STRING(255), allowNull: false }, coverMessage: { type: DataTypes.TEXT, field: 'cover_message' }, status: { type: DataTypes.ENUM('baru', 'ditinjau', 'lolos', 'tidak_lolos', 'diterima'), defaultValue: 'baru' } }, { tableName: 'applications' });
const Gallery = sequelize.define('Gallery', { title: { type: DataTypes.STRING(180), allowNull: false }, image: { type: DataTypes.STRING(255), allowNull: false }, description: DataTypes.TEXT, category: DataTypes.STRING(120), eventDate: { type: DataTypes.DATEONLY, field: 'event_date' }, status: { type: DataTypes.ENUM('draft', 'published'), defaultValue: 'draft' } }, { tableName: 'galleries' });
const Article = sequelize.define('Article', { title: { type: DataTypes.STRING(220), allowNull: false }, slug: { type: DataTypes.STRING(260), allowNull: false, unique: true }, thumbnail: DataTypes.STRING(255), content: { type: DataTypes.TEXT('long'), allowNull: false }, category: DataTypes.STRING(120), author: { type: DataTypes.STRING(120), allowNull: false }, status: { type: DataTypes.ENUM('draft', 'published'), defaultValue: 'draft' }, publishedAt: { type: DataTypes.DATE, field: 'published_at' } }, { tableName: 'articles' });

Company.hasMany(Job, { foreignKey: 'companyId', as: 'jobs', onDelete: 'CASCADE' });
Job.belongsTo(Company, { foreignKey: 'companyId', as: 'company' });
Job.hasMany(Application, { foreignKey: 'jobId', as: 'applications', onDelete: 'CASCADE' });
Application.belongsTo(Job, { foreignKey: 'jobId', as: 'job' });

module.exports = { sequelize, Admin, Company, Job, Application, Gallery, Article };
