CREATE TABLE db_bkk.admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(160) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE db_bkk.companies (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, logo VARCHAR(255), description TEXT, website VARCHAR(255), email VARCHAR(160), phone VARCHAR(30), address TEXT, industry VARCHAR(120), status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE db_bkk.jobs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id INT UNSIGNED NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(220) NOT NULL UNIQUE, image VARCHAR(255), location VARCHAR(160) NOT NULL, job_type VARCHAR(80) NOT NULL, description TEXT NOT NULL, requirements TEXT NOT NULL, skills TEXT NOT NULL, education VARCHAR(180) NOT NULL, salary VARCHAR(255), deadline DATE, status ENUM('draft','published','closed') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, FOREIGN KEY (company_id) REFERENCES db_bkk.companies(id) ON UPDATE CASCADE ON DELETE RESTRICT);
CREATE TABLE db_bkk.applications (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_id INT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, nisn VARCHAR(30) NOT NULL, whatsapp VARCHAR(30) NOT NULL, email VARCHAR(160) NOT NULL, graduation_year SMALLINT NOT NULL, average_score DECIMAL(5,2) NOT NULL, major VARCHAR(160) NOT NULL, main_skill VARCHAR(160) NOT NULL, cv VARCHAR(255) NOT NULL, diploma VARCHAR(255) NOT NULL, cover_message TEXT, status ENUM('baru','ditinjau','lolos','tidak_lolos','diterima') NOT NULL DEFAULT 'baru', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, FOREIGN KEY (job_id) REFERENCES db_bkk.jobs(id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE db_bkk.galleries (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, image VARCHAR(255) NOT NULL, description TEXT, category VARCHAR(120), event_date DATE, status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE db_bkk.articles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(220) NOT NULL, slug VARCHAR(260) NOT NULL UNIQUE, thumbnail VARCHAR(255), content LONGTEXT NOT NULL, category VARCHAR(120), author VARCHAR(120) NOT NULL,
status ENUM('draft','published') NOT NULL DEFAULT 'draft', published_at DATETIME NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL);
